/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaco Coetsee
 */
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ExerciseGUI extends javax.swing.JFrame {
    private javax.swing.JFormattedTextField[] currents;
    private javax.swing.JFormattedTextField[] goals;
    private javax.swing.JLabel[] labels;
    private javax.swing.JProgressBar[] progBars;
    private javax.swing.JButton[] logButts;
    private javax.swing.JButton[] statButts;
    private int exercises = 0;
    private Exercises ex = new Exercises();
    /**
     * Creates new form ExerciseGUI
     */
    public ExerciseGUI() {
        initComponents();
        populateArrays();
        try {
            populateFields();
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exercise1Label = new javax.swing.JLabel();
        exercise3Label = new javax.swing.JLabel();
        exercise2Label = new javax.swing.JLabel();
        exercise5Label = new javax.swing.JLabel();
        exercise4Label = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 0), new java.awt.Dimension(80, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        exProgress4 = new javax.swing.JProgressBar();
        exProgress1 = new javax.swing.JProgressBar();
        exProgress3 = new javax.swing.JProgressBar();
        exProgress2 = new javax.swing.JProgressBar();
        exProgress5 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        exGoal1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        exCurrent1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        exGoal2 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        exCurrent2 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        exGoal3 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        exCurrent3 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        exGoal4 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        exCurrent4 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        exGoal5 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        exCurrent5 = new javax.swing.JFormattedTextField();
        exStatsButton1 = new javax.swing.JButton();
        exLogButton1 = new javax.swing.JButton();
        exStatsButton2 = new javax.swing.JButton();
        exLogButton2 = new javax.swing.JButton();
        exStatsButton3 = new javax.swing.JButton();
        exLogButton3 = new javax.swing.JButton();
        exLogButton4 = new javax.swing.JButton();
        exStatsButton4 = new javax.swing.JButton();
        exLogButton5 = new javax.swing.JButton();
        exStatsButton5 = new javax.swing.JButton();
        addExButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        exercise1Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exercise1Label.setText("Exercise 1");

        exercise3Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exercise3Label.setText("Exercise 3");

        exercise2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exercise2Label.setText("Exercise 2");

        exercise5Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exercise5Label.setText("Exercise 5");

        exercise4Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exercise4Label.setText("Exercise 4");

        jLabel1.setText("Goal:");

        exGoal1.setText("0");

        jLabel2.setText("Current:");

        exCurrent1.setText("0");

        jLabel3.setText("Goal:");

        exGoal2.setText("0");

        jLabel4.setText("Current:");

        exCurrent2.setText("0");

        jLabel5.setText("Goal:");

        exGoal3.setText("0");

        jLabel6.setText("Current:");

        exCurrent3.setText("0");

        jLabel7.setText("Goal:");

        exGoal4.setText("0");

        jLabel8.setText("Current:");

        exCurrent4.setText("0");

        jLabel9.setText("Goal:");

        exGoal5.setText("0");

        jLabel10.setText("Current:");

        exCurrent5.setText("0");

        exStatsButton1.setText("Stats");
        exStatsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exStatsButton1ActionPerformed(evt);
            }
        });

        exLogButton1.setText("Log");
        exLogButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exLogButton1ActionPerformed(evt);
            }
        });

        exStatsButton2.setText("Stats");
        exStatsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exStatsButton2ActionPerformed(evt);
            }
        });

        exLogButton2.setText("Log");
        exLogButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exLogButton2ActionPerformed(evt);
            }
        });

        exStatsButton3.setText("Stats");
        exStatsButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exStatsButton3ActionPerformed(evt);
            }
        });

        exLogButton3.setText("Log");
        exLogButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exLogButton3ActionPerformed(evt);
            }
        });

        exLogButton4.setText("Log");
        exLogButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exLogButton4ActionPerformed(evt);
            }
        });

        exStatsButton4.setText("Stats");
        exStatsButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exStatsButton4ActionPerformed(evt);
            }
        });

        exLogButton5.setText("Log");
        exLogButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exLogButton5ActionPerformed(evt);
            }
        });

        exStatsButton5.setText("Stats");
        exStatsButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exStatsButton5ActionPerformed(evt);
            }
        });

        addExButton.setText("Add Exercise");
        addExButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove Exercise");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        modifyButton.setText("Modify Goal");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Exercise Logger 1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exercise3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exercise2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exercise5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exercise4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exProgress4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exProgress3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exProgress2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exProgress5, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(exGoal1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(exCurrent1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(exercise1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(exGoal2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exCurrent2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(exGoal3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exCurrent3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(exGoal4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exCurrent4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(exGoal5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exCurrent5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exLogButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exStatsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exLogButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exStatsButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exLogButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exStatsButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exLogButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exStatsButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(exLogButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exStatsButton5)))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addExButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addExButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(exercise1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exGoal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exCurrent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exStatsButton1))
                        .addGap(8, 8, 8)
                        .addComponent(exProgress1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exLogButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exercise2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exGoal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exCurrent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exProgress2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(exStatsButton2)
                            .addGap(39, 39, 39))
                        .addComponent(exLogButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exercise3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exGoal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exCurrent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(exProgress3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exStatsButton3)
                        .addGap(39, 39, 39))
                    .addComponent(exLogButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exercise4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exGoal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exCurrent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(exProgress4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exStatsButton4)
                        .addGap(39, 39, 39))
                    .addComponent(exLogButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exercise5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exGoal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exCurrent5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exProgress5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exStatsButton5)
                        .addGap(39, 39, 39))
                    .addComponent(exLogButton5))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addExButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExButtonActionPerformed
        if(exercises >= 5){
            JOptionPane.showMessageDialog(null, "You already have the maximum number of exercises"); 
        }else{
           addExerciseMenu aem = new addExerciseMenu();
           aem.setVisible(true);
           dispose();
        }
    }//GEN-LAST:event_addExButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        updateExercises();
        if(exercises == 0){
            JOptionPane.showMessageDialog(null, "You don't have any exercises"); 
        }else{
            String[] allLabels = getLabelNames();
            deleteExercise de = new deleteExercise(allLabels, exercises);
            de.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        updateExercises();
        if(exercises == 0){
            JOptionPane.showMessageDialog(null, "You don't have any exercises to modify goals of."); 
        }else{
            String[] allLabels = getLabelNames();
            goalModifier gm = new goalModifier(allLabels, exercises);
            gm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void exStatsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exStatsButton1ActionPerformed
        genericStats gl = new genericStats(ex.getIDOfIndex(0), exercise1Label.getText());
        gl.setVisible(true);
        dispose();
    }//GEN-LAST:event_exStatsButton1ActionPerformed

    private void exStatsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exStatsButton2ActionPerformed
        genericStats gl = new genericStats(ex.getIDOfIndex(1), exercise2Label.getText());
        gl.setVisible(true);
        dispose();
    }//GEN-LAST:event_exStatsButton2ActionPerformed

    private void exStatsButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exStatsButton3ActionPerformed
        genericStats gl = new genericStats(ex.getIDOfIndex(2), exercise3Label.getText());
        gl.setVisible(true);
        dispose();
    }//GEN-LAST:event_exStatsButton3ActionPerformed

    private void exStatsButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exStatsButton4ActionPerformed
        genericStats gl = new genericStats(ex.getIDOfIndex(3), exercise4Label.getText());
        gl.setVisible(true);
        dispose();
    }//GEN-LAST:event_exStatsButton4ActionPerformed

    private void exStatsButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exStatsButton5ActionPerformed
        genericStats gl = new genericStats(ex.getIDOfIndex(4), exercise5Label.getText());
        gl.setVisible(true);
        dispose();
    }//GEN-LAST:event_exStatsButton5ActionPerformed

    private void exLogButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exLogButton1ActionPerformed
        try {
            genericLog gs = new genericLog(ex.getIDOfIndex(0), exercise1Label.getText());
            gs.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exLogButton1ActionPerformed

    private void exLogButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exLogButton2ActionPerformed
        try {
            genericLog gs = new genericLog(ex.getIDOfIndex(1), exercise2Label.getText());
            gs.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exLogButton2ActionPerformed

    private void exLogButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exLogButton3ActionPerformed
        try {
            genericLog gs = new genericLog(ex.getIDOfIndex(2), exercise3Label.getText());
            gs.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exLogButton3ActionPerformed

    private void exLogButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exLogButton4ActionPerformed
        try {
            genericLog gs = new genericLog(ex.getIDOfIndex(3), exercise4Label.getText());
            gs.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exLogButton4ActionPerformed

    private void exLogButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exLogButton5ActionPerformed
        try {
            genericLog gs = new genericLog(ex.getIDOfIndex(4), exercise5Label.getText());
            gs.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exLogButton5ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        ex = new Exercises();
        try {
            populateFields();
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerciseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerciseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerciseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerciseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerciseGUI().setVisible(true);
            }
        });
    }
    public void getNewExercise(exValues ex1){
        try {
            ex.addExercise(ex1);
            populateArrays();
            populateFields();
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void deleteExercise(int i){
        try {
            ex.deleteExercise(i);
            populateArrays();
            populateFields();
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void modiffyExercise(int i, int newGoal){
        try {
            ex.modifyExercise(i, newGoal);
            populateArrays();
            populateFields();
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void populateArrays(){
       currents = new javax.swing.JFormattedTextField[]{exCurrent1,exCurrent2, exCurrent3, exCurrent4, exCurrent5};
       goals = new javax.swing.JFormattedTextField[]{exGoal1,exGoal2, exGoal3, exGoal4, exGoal5};
       progBars = new javax.swing.JProgressBar[]{exProgress1,exProgress2, exProgress3, exProgress4, exProgress5};
       labels = new javax.swing.JLabel[]{exercise1Label,exercise2Label, exercise3Label, exercise4Label, exercise5Label};
       statButts = new javax.swing.JButton[]{exStatsButton1,exStatsButton2,exStatsButton3,exStatsButton4,exStatsButton5};
       logButts = new javax.swing.JButton[]{exLogButton1,exLogButton2,exLogButton3,exLogButton4,exLogButton5};
    }
    private void clearAll(){
        for(int i = 0; i < 5; i ++){
            currents[i].setText(0 + "");
            goals[i].setText(0 + "");
            progBars[i].setValue(0);
            labels[i].setText("Exercise " + (i+1));
            statButts[i].setVisible(false);
            logButts[i].setVisible(false);
        }
    }
    private void populateFields() throws SQLException{
        clearAll();
        exercises = ex.getNumberOfExercises();
        for(int i = 0; i < exercises; i++){
            goals[i].setText(ex.getFieldValues(i, 0) + "");
            currents[i].setText(ex.getFieldValues(i, 1) + "");
            progBars[i].setMaximum(Integer.parseInt(ex.getFieldValues(i, 0)));
            progBars[i].setValue(Integer.parseInt(ex.getFieldValues(i, 1)));
            labels[i].setText(ex.getFieldValues(i,2));
            statButts[i].setVisible(true);
            logButts[i].setVisible(true);
        }
    }
    private void updateExercises(){
        try {
            exercises = ex.getNumberOfExercises();
        } catch (SQLException ex) {
            Logger.getLogger(ExerciseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private String[] getLabelNames(){
        String[] labelArray = new String[exercises];
        for(int i = 0; i < exercises; i ++){
            labelArray[i] = labels[i].getText();
        }
        return labelArray;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExButton;
    private javax.swing.JFormattedTextField exCurrent1;
    private javax.swing.JFormattedTextField exCurrent2;
    private javax.swing.JFormattedTextField exCurrent3;
    private javax.swing.JFormattedTextField exCurrent4;
    private javax.swing.JFormattedTextField exCurrent5;
    private javax.swing.JFormattedTextField exGoal1;
    private javax.swing.JFormattedTextField exGoal2;
    private javax.swing.JFormattedTextField exGoal3;
    private javax.swing.JFormattedTextField exGoal4;
    private javax.swing.JFormattedTextField exGoal5;
    private javax.swing.JButton exLogButton1;
    private javax.swing.JButton exLogButton2;
    private javax.swing.JButton exLogButton3;
    private javax.swing.JButton exLogButton4;
    private javax.swing.JButton exLogButton5;
    private javax.swing.JProgressBar exProgress1;
    private javax.swing.JProgressBar exProgress2;
    private javax.swing.JProgressBar exProgress3;
    private javax.swing.JProgressBar exProgress4;
    private javax.swing.JProgressBar exProgress5;
    private javax.swing.JButton exStatsButton1;
    private javax.swing.JButton exStatsButton2;
    private javax.swing.JButton exStatsButton3;
    private javax.swing.JButton exStatsButton4;
    private javax.swing.JButton exStatsButton5;
    private javax.swing.JLabel exercise1Label;
    private javax.swing.JLabel exercise2Label;
    private javax.swing.JLabel exercise3Label;
    private javax.swing.JLabel exercise4Label;
    private javax.swing.JLabel exercise5Label;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
